version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    restart: unless-stopped

  tg_gateway:
    build: ./tg_gateway
    container_name: tg_gateway
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis
    restart: unless-stopped

  bridge:
    build: ./bridge
    container_name: tg_bridge
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis
    restart: unless-stopped

  bitrix_connector:
    build: ./bitrix_connector
    container_name: bitrix_connector
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis
    restart: unless-stopped